require 'qapi/github/query/organization_query'
require 'qapi/github/query/user_query'
require 'qapi/github/query/repo_query'
require 'qapi/github/query/repo_status_query'
require 'qapi/github/query/pull_request_query'
